language: python
python:
    - 2.7
install:
    # Travis's pre-installed pip and pytest are too old:
    # https://docs.travis-ci.com/user/languages/python/#Pre-installed-packages
    - pip install codecov
    - python setup.py install
    - ln -s tests/lain.yaml lain.yaml
script: py.test --cov=lain_cli

after_success:
    - codecov
